kind: pipeline
type: kubernetes
name: Discover GitHub releases
steps:
  - name: Discover releases
    image: golang:1.18.2-alpine
    commands:
      - go run ./cmd/discover_releases/main.go
  - name: Promote
    image: ubuntu
    environment:
      DRONE_SERVER: http://drone
      DRONE_TOKEN:
        from_secret: drone_token
      ENVIRONMENT: staging
      FILE: tags.txt
    commands:
      - curl -L https://github.com/harness/drone-cli/releases/latest/download/drone_linux_amd64.tar.gz | tar zx
      - install -t /usr/local/bin drone
      - sh scripts/promote.sh

---
kind: pipeline
type: kubernetes
name: Publish
trigger:
  event: 
    - promote
  target:
    - staging
steps:
  - name: Clone
    image: alpine/git
    commands:
      - git clone --depth 1 --branch $TAG https://github.com/harness/drone.git drone
  - name: Build
    image: golang:1.14.15
    environment:
      GOARCH: amd64
      GOOS: linux
    commands:
      - sh scripts/build.sh
  - name: Publish Docker image
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile.server.linux.amd64
      dry_run: true
      repo: dockcenter/drone
      tags: $TAG
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password