kind: pipeline
type: kubernetes
name: Build Docker image
steps:
  - name: Discover releases
    image: golang:1.18.2-alpine
    commands:
      - go run ./cmd/discover_releases/main.go
  - name: Print tags.txt
    image: busybox
    commands:
      - ls
      - cat tags.txt